version: '3.8'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        env_file: dev.env
        command: bash -c "
            /home/app/wait-for-it.sh db:5432 -t 0 &&
            python manage.py makemigrations --noinput &&
            python manage.py migrate --noinput &&
            python manage.py collectstatic --noinput &&
            python manage.py run_rebuild_core &&
            gunicorn config.wsgi:application --bind 0.0.0.0:8000 --reload
            "
        volumes:
            - .:/home/app/
            - static_volume:/home/app/staticfiles/
            - media_volume:/home/app/media/
            - logs_volume:/home/app/logs/
        networks:
            web:
                aliases:
                    - web
        ports:
            - 8000:8000
        depends_on:
            - db

    db:
        image: postgres:13.1-alpine
        hostname: db
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        networks:
            - web
        ports:
            - 5432:5432

networks:
    web:

volumes:
    static_volume:
    media_volume:
    logs_volume:
    postgres_data:
